---
kind: pipeline
type: docker
name: default

steps:
  - name: publish-one
    image: registry.example.com/drone-bazelisk-ecr
    volumes:
      - name: cache
        path: /cache
    settings:
      target: :push_one
      bazelrc: .bazelrc.drone
      tag: one
      create_repository: true
      repository: drone-bazelisk-ecr-example-one
      registry:
        from_secret: ECR_REGISTRY
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY

  - name: publish-two
    image: registry.example.com/drone-bazelisk-ecr
    volumes:
      - name: cache
        path: /cache
    settings:
      target: :push_two
      bazelrc: .bazelrc.drone
      tag: two
      create_repository: true
      repository: drone-bazelisk-ecr-example-two
      registry:
        from_secret: ECR_REGISTRY
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY

volumes:
  - name: cache
    temp: {}
