---
kind: pipeline
name: test
trigger:
  branch: [master]
workspace:
  path: /go/src/github.com/${DRONE_REPO}
steps:
  - name: test
    image: golangci/golangci-lint:v1.51.2-alpine
    commands:
      - apk add make
      - make test

  - name: license-check
    image: public.ecr.aws/kanopy/licensed-go:3.4.4
    commands:
      - licensed cache
      - licensed status

---
kind: pipeline
name: build-amd64
platform:
  arch: amd64
trigger:
  branch: [master]
  event: [pull_request]
depends_on:
  - test
steps:
  - name: build
    image: plugins/kaniko-ecr
    pull: always
    settings:
      no_push: true
      build_args:
        - ARCH=amd64

---
kind: pipeline
name: build-arm64
platform:
  arch: arm64
trigger:
  branch: [master]
  event: [pull_request]
depends_on:
  - test
steps:
  - name: build
    image: plugins/kaniko-ecr
    pull: always
    settings:
      no_push: true
      build_args:
        - ARCH=arm64

---
kind: pipeline
name: publish-amd64
platform:
  arch: amd64
depends_on:
  - test
trigger:
  branch: master
  event: [push, tag]
steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy
      repo: ${DRONE_REPO_NAME}
      auto_tag: true
      auto_tag_suffix: amd64
      build_args:
        - ARCH=amd64
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key

---
kind: pipeline
name: publish-arm64
platform:
  arch: arm64
depends_on:
  - test
trigger:
  branch: master
  event: [push, tag]
steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy
      repo: ${DRONE_REPO_NAME}
      auto_tag: true
      auto_tag_suffix: arm64
      build_args:
        - ARCH=arm64
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
