---
kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
    - master

steps:
  - name: test
    image: golang:1.19
    commands:
      - go vet ./...
      - go test ./...

  - name: publish_push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-bazelisk-ecr
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push

  - name: publish_tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-bazelisk-ecr
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
